name: Main Frontend Workflow

on:
  push:
    branches:
      - main
      - dev 
      #- feature/*

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy to Dev
    #Not necessary but just more secure if workflow changes are made
    if: github.ref == 'refs/heads/dev' 
    uses: ./.github/workflows/frontend-deploy.yml
    with:
      environment: dev
      aws_account_id: "474668415523"
    secrets:
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}
      COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID_DEV }}
      COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID_DEV }}
      STREAMLIT_URL: ${{ secrets.STREAMLIT_URL }}

  deploy-prod:
    name: Deploy to Prod
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/frontend-deploy.yml
    with:
      environment: prod
      aws_account_id: "054037129431"
    secrets:
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }}
      COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID_PROD }}
      COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID_PROD }}
      STREAMLIT_URL: ${{ secrets.STREAMLIT_URL }}
