name: Main Frontend Workflow

on:
  push:
    branches:
      - main
      - develop
      - "feature/*"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy to Dev
    uses: ./.github/workflows/frontend-deploy.yml
    with:
      environment: dev
      aws_account_id: "474668415523"
    secrets:
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}
      COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID_DEV }}
      COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID_DEV }}
      STREAMLIT_URL: ${{ secrets.STREAMLIT_URL_DEV }}
      API_URL: ${{ secrets.API_URL_DEV }}

  deploy-prod:
    name: Deploy to Prod
    needs: deploy-dev
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/frontend-deploy.yml
    with:
      environment: prod
      aws_account_id: "054037129431"
    secrets:
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }}
      COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID_PROD }}
      COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID_PROD }}
      STREAMLIT_URL: ${{ secrets.STREAMLIT_URL_PROD }}
      API_URL: ${{ secrets.API_URL_PROD }}
