name: Frontend Deployment (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
    secrets:
      CLOUDFRONT_DISTRIBUTION_ID:
        required: true
      COGNITO_USER_POOL_ID:
        required: true
      COGNITO_CLIENT_ID:
        required: true
      STREAMLIT_URL:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      TF_VERSION: "1.11.0-rc3"
      AWS_REGION: "eu-west-2"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{inputs.aws_account_id}}:role/GitHubFrontendDeployRole
          role-session-name: GitHubFrontendSession
          aws-region: ${{ env.AWS_REGION }}

      # Create .env file with environment variables
      - name: Create .env file
        run: |
          echo "VITE_COGNITO_USER_POOL_ID=${{ secrets.COGNITO_USER_POOL_ID }}" > .env
          echo "VITE_COGNITO_CLIENT_ID=${{ secrets.COGNITO_CLIENT_ID }}" >> .env
          echo "VITE_COGNITO_DOMAIN=studentportal-${{ inputs.aws_account_id }}" >> .env
          echo "VITE_STREAMLIT_URL=${{ secrets.STREAMLIT_URL }}" >> .env
          cat .env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Sync S3 bucket
        run: aws s3 sync ./dist s3://studentportal-frontend-bucket-474668415523 --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
